### ISSUE TITLE
Use mail() instead of SMTP

### ISSUE THREAD

**Issue by Ansem** [masterking32/WoWSimpleRegistration#15]
Is it possible to use PHP's build-in send mail() function instead of setting up a seperate SMTP server?

Thanks in advance.

**Comment by masterking32** [comment]
Hey,
Yes we use SMTP, because some people don't have mail server or spam issues.
You can replace this funcation to something like that:
https://github.com/masterking32/WoWSimpleRegistration/blob/master/application/include/functions.php#L123

`function send_phpmailer($email, $subject, $message)
{
	$headers = "MIME-Version: 1.0" . "\r\n";
	$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";

	// More headers
	$headers .= 'From: <webmaster@YOUR-DOMAIN.com>' . "\r\n";
	
	mail($email,$subject,$message,$headers);
	
    return true;
}`
